# Generated by Django 5.1.3 on 2024-12-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_reactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions',
            old_name='users',
            new_name='user',
        ),
    ]
